apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: pipeline
  name: pipeline
  namespace: default
spec:
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - image: gcr.io/jk-example-project/pipeline:9773718729c51797d5c12408cd360f5cdb427a90
        name: pipeline
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
